-- This file has been generated by Dungeon Editor 2.1.18

-- TODO: place your custom dungeon object definitions here

defineObject{
	components = {
		{
			offset = {
				0,
				1.375,
				-0.12,
				0
			},
			staticShadow = true,
			class = "Model",
			name = "model",
			model = "assets/models/env/mine_lock.fbx"
		}
	},	
	editorIcon = 20,
	baseObject = "mine_lock",
	name = "pirate_lock",
	placement = "wall"
}

defineObject{
	baseObject = "receptor",
	name = "height_receptor",
	components = {
		{
			offset = {
				0,
				1.2,
				-0.25,
				0
			},
			staticShadow = true,
			class = "Model",
			name = "model",
			model = "assets/models/env/spell_receptor.fbx"
		}
	}
}

defineObject{
	baseObject = "castle_wall_cloth",
	name = "red_flag",
	components = {
		{
			model = "assets/models/env/castle_wall_cloth.fbx",
			name = "model",
			class = "Model",
			offset = {
				0,
				-0.25,
				0,
				0
			}
		}
	}
}

defineObject{
	baseObject = "base_door_sparse",
	components = {
		{
			model = "assets/models/env/castle_door_porticullis.fbx",
			class = "Model",
			name = "model",
			enabled = false
		},
		{
			onAttackedByChampion = function()
				for e in party.map:entitiesAt(party.x, party.y) do
						if e.script and e.script.onAttacked then
							e.script:onAttacked()
						end
					end
				end,
			name = "door",
			openVelocity = 1.3,
			closeVelocity = 0,
			class = "Door",
			closeAcceleration = -10,
			sparse = true
		}
	},
	name = "attack_trigger",
	automapIcon = -1
}