-- This file has been generated by Dungeon Editor 2.1.18

-- TODO: place your custom spell definitions here

defineObject{
	baseObject = "base_spell",
	name = "signal",
	components = {
		{
			particleSystem = "blob",
			name = "particle",
			class = "Particle"
		},
		{
			velocity = 10,
			hitEffect = "signal_blast",
			name = "projectile",
			class = "Projectile",
			radius = 0.1,
			spawnOffsetY = 1.35
		},
		{
			sound = "lightning_bolt",
			class = "Sound",
			name = "sound"
		},
		{
			sound = "lightning_bolt_launch",
			class = "Sound",
			name = "launchSound"
		}
	}
}

defineObject{
	baseObject = "base_spell",
	name = "signal_blast",
	components = {
		{
			destroyObject = true,
			class = "Particle",
			name = "particle",
			particleSystem = "blob_hit"
		},
		{
			damageType = "shock",
			woundChance = 10,
			sound = "lightning_bolt_hit_small",
			class = "TileDamager",
			name = "tiledamager",
			attackPower = 1
		}
	}
}

defineSpell {
	name = "signal",
	uiName = "Signal",
	gesture = 236,
	manaCost = 0,
	icon = 72,
	spellIcon = 13,
	description = "Universal naval signal.",
	onCast = function(champion, x, y, direction, elevation, skillLevel)
		local lx, ly = getForward(direction)		
		spawn("signal", party.level, x + lx, y + ly, direction, elevation)
	end
}

defineObject{
	baseObject = "base_spell",
	name = "signal_secret",
	components = {
		{
			particleSystem = "dark_bolt",
			name = "particle",
			class = "Particle"
		},
		{
			velocity = 10,
			hitEffect = "signal_secret_blast",
			name = "projectile",
			class = "Projectile",
			radius = 0.1,
			spawnOffsetY = 1.35,
		},
		{
			sound = "dark_bolt",
			class = "Sound",
			name = "sound"
		},
		{
			sound = "dark_bolt_launch",
			class = "Sound",
			name = "launchSound"
		}
	}
}

defineObject{
	baseObject = "base_spell",
	name = "signal_secret_blast",
	components = {
		{
			destroyObject = true,
			class = "Particle",
			name = "particle",
			particleSystem = "dark_bolt_hit"
		},
		{
			class = "TileDamager",			
			sound = "dark_bolt_hit",
			name = "tiledamager",
			attackPower = 0
		}
	}
}

defineSpell {
	name = "signal_secret",
	uiName = "Secret Signal",
	gesture = 145,
	manaCost = 0,
	icon = 59,
	spellIcon = 11,
	description = "Secret signal that only pirates understand.",
	onCast = function(champion, x, y, direction, elevation, skillLevel)
		local lx, ly = getForward(direction)		
		spawn("signal_secret", party.level, x + lx, y + ly, direction, elevation)
	end
}

defineObject{
	name = "wall_fire_strong",
	baseObject = "wall_fire",
	components = {
		{
			class = "TileDamager",
			attackPower = 50,
			damageType = "fire",
			repeatCount = 5,
			repeatDelay = 4.3/5,
		},
	},
}

defineSpell {
	name = "future",
	uiName = "Look into the future",
	gesture = 74569,
	manaCost = 0,
	icon = 72,
	spellIcon = 13,
	description = "Fortunetellers make fortune using these. Maybe that is why they are called fortune-tellers.",
	onCast = function(champion, x, y, direction, elevation, skillLevel)
		hudPrint("Do you believe in this stuff?")
	end
}

defineSpell {
	name = "make_torn_cloth",
	uiName = "Make Torn Cloth",
	gesture = 7896,
	manaCost = 15,
	icon = 11,
	spellIconAtlas = "mod_assets/textures/spell_icons.tga",
	spellIcon = 20,
	description = "Tear clothes into nice stripes used for making torches.",
	onCast = function(champion, x, y, direction, elevation, skillLevel)
		local slot = 1
		local item = champion:getItem(slot)
		if item == nil or not item:hasTrait("clothes") then
			slot = 2
			item = champion:getItem(slot)
		end			
		if item ~= nil and item:hasTrait("clothes") then
			local stripes = math.ceil(item:getWeight() / 0.3)
			if stripes > 0 then
				local cloth = helper.script._spawn("torn_cloth")
				cloth.item:setStackSize(stripes)
				champion:removeItemFromSlot(slot)
				champion:insertItem(slot, cloth.item)
				champion:gainExp(50)
			end
		else
			helper.script.talkRandom(champion:getName(), {
					"I am not going to do this under such conditions.",
					"Tear what? I need clothes for this.",
					"This will not work.",
					"I need to grab some shirt and tear it to pieces.",
					"Better give me your pants and then you'll see!"
				}
			)
		end
	end
}

defineObject{
   name ="projectile_arrow",
   baseObject = "base_spell",
   components = {
	  {
		 class = "Model",
		 model = "assets/models/items/arrow.fbx",
		 rotation = vec(0,90,0)
	  },
	  {
		 class = "Projectile",
		 spawnOffsetY = 1.15,
		 velocity = 15.0,
		 radius = 0.1,
		 hitEffect = "projectile_arrow_hit",
	  },
	  {
		 class = "Sound",
		 name = "launchSound",
		 sound = "swipe_bow",
	  }
   },
}

defineObject{
   name = "projectile_arrow_hit",
   baseObject = "base_spell",
   components = {
	 {
		 class = "TileDamager",
		 attackPower = 10,
		 damageType = "physical",
		 screenEffect = "damage_screen",
		 sound = "projectile_hit_party",
	  }
   },
}
	
defineObject{
	name = "cannon_shot",
	baseObject = "base_spell",
	components = {
		{
			class = "Particle",
			particleSystem = "fireball_large",
		},
		{
			class = "Light",
			color = vec(1, 0.5, 0.25),
			brightness = 25,
			range = 17,
			castShadow = true,
		},
		{
			class = "Projectile",
			spawnOffsetY = 1.35,
			velocity = 15,
			radius = 0.2,
			hitEffect = "fireball_blast_large",
			gravity = 0.6
		},
		{
			class = "Sound",
			sound = "fireball",
		},
		{
			class = "Sound",
			name = "launchSound",
			sound = "fireball_launch",
		},
	},
}