-- This file has been generated by Dungeon Editor 2.1.18

-- TODO: place your custom item definitions here

defineObject{
	baseObject = "base_item",
	name = "steel_helmet",
	components = {
		{
			model = "assets/models/items/skeleton_helmet.fbx",
			name = "model",
			class = "Model"
		},
		{
			weight = 2.4,
			uiName = "Steel Helmet",
			gfxIndex = 209,
			class = "Item",
			name = "item",
			traits = {
				"heavy_armor",
				"helmet"
			}
		},
		{
			class = "EquipmentItem",
			protection = 10,
			name = "equipmentitem",
			immunities = {				
				"paralyzed",				
				"blind",
				"petrified"
			}
		}
	}
}

defineObject{
	baseObject = "base_item",
	name = "steel_cuirass",
	components = {
		{
			model = "assets/models/items/plate_cuirass.fbx",
			name = "model",
			class = "Model"
		},
		{
			weight = 16,
			uiName = "Steel Cuirass",
			gfxIndex = 91,
			class = "Item",
			name = "item",
			traits = {
				"heavy_armor",
				"chest_armor"
			}
		},
		{
			class = "EquipmentItem",
			protection = 20,
			name = "equipmentitem"
		}
	}
}

defineObject {
	name = "pirate_machete",
	baseObject = "machete",
	
	components = {
		{
			class = "Item",
			name="item",
			uiName = "Pirate Machete",
			description = "This is a great tool when you need to clear way in a jungle. However, there is also some old dry blood on this machete.",
			gfxIndex = 23,
			weight = 2,
			impactSound = "impact_blade",
			traits = {
				"heavy_weapon",
				"aquatic"
			},
		},
		{
			name = "meleeattack",
			attackSound = "swipe_light",
			swipe = "vertical",
			cooldown = 1.5,
			class = "MeleeAttack",			
			attackPower = 17,
            requirements = {
				"heavy_weapons",
				1
			},
		}
	}
	
}

defineObject {
	name = "woodcutting_axe",
	baseObject = "hand_axe",
	
	components = {
		{
			class = "Item",
			name="item",
			uiName = "Woodcutting Axe",
			description = "Sometimes pirates use it for cutting arms or heads as well.",
			gfxIndex = 25,
			weight = 2.5,
			impactSound = "impact_blade",
			traits = {
				"light_weapon",
				"aquatic"
			},
		},
		{
			name = "meleeattack",
			attackSound = "swipe_light",
			swipe = "vertical",
			cooldown = 2.5,
			class = "MeleeAttack",			
			attackPower = 12,
            requirements = {
				"light_weapons",
				1
			},
		}
	}	
}

defineObject{
	baseObject = "base_item",
	name = "pirate_rifle",
	components = {
		{
			model = "assets/models/items/arquebus.fbx",
			name = "model",
			class = "Model"
		},
		{
			impactSound = "impact_blunt",
			weight = 3.5,
			traits = {
				"firearm"
			},
			uiName = "Pirate Musket",
			gfxIndex = 331,
			class = "Item",
			name = "item",
			description = "This large rifle packs enough punch to blast a hole through the hull of a ratling caravel."
		},
		{
			backfireChance = 1,
			damageType = "shock",
			name = "firearmattack",
			ammo = "pellet",
			cooldown = 6,
			attackSound = "gun_shot_large",
			class = "FirearmAttack",
			requirements = {
				"firearms",
				2
			},
			attackPower = 35
		}
	}
}